# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: nvm use default && npm install -g near-shell@0.23.2
    command: yarn && brew install tree && clear && echo Welcome to Exploring AssemblyScript Contracts with NEAR Protocol
